-- Esquema bd_registro migrado de MariaDB (10.4) a PostgreSQL
-- Generado automaticamente. Aplicar en Supabase.

--

--
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla admin
--

CREATE TABLE admin (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  usuario varchar(100) NOT NULL,
  clave varchar(100) NOT NULL
) ;

--
-- Volcado de datos para la tabla admin
--

INSERT INTO admin (id, usuario, clave) VALUES
(1, 'administrador', 'administrador123');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla comentarios
--

CREATE TABLE comentarios (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  usuario_id integer DEFAULT NULL,
  nombre_usuario varchar(100) DEFAULT NULL,
  comentario text NOT NULL,
  fecha timestamp DEFAULT current_timestamp
) ;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla compras_proveedores
--

CREATE TABLE compras_proveedores (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  proveedor_id integer NOT NULL,
  producto_id integer NOT NULL,
  cantidad integer NOT NULL CHECK (cantidad > 0),
  precio_unitario numeric(10,2) NOT NULL,
  fecha_registro timestamp NOT NULL DEFAULT current_timestamp,
  estado varchar(50) DEFAULT 'pendiente'
) ;

--
-- Volcado de datos para la tabla compras_proveedores
--

INSERT INTO compras_proveedores (id, proveedor_id, producto_id, cantidad, precio_unitario, fecha_registro, estado) VALUES
(2, 1, 122, 20, 60.00, '2025-07-21 21:30:05', 'pendiente'),
(3, 1, 122, 20, 60.00, '2025-07-21 21:30:48', 'pendiente'),
(4, 6, 6, 50, 50.00, '2025-07-21 21:45:23', 'pendiente'),
(5, 6, 6, 50, 50.00, '2025-07-21 21:45:26', 'pendiente'),
(6, 7, 1, 6, 30.00, '2025-07-21 22:04:50', 'pendiente'),
(7, 7, 19, 30, 13.00, '2025-07-21 22:06:47', 'pendiente'),
(8, 8, 37, 40, 2.00, '2025-07-21 22:27:20', 'pendiente');

--
-- Disparadores compras_proveedores
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla historial_admin
--

CREATE TABLE historial_admin (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  usuario_admin varchar(100) NOT NULL,
  accion varchar(20) NOT NULL,
  tabla_afectada varchar(50) NOT NULL,
  id_afectado integer DEFAULT NULL,
  detalles text DEFAULT NULL,
  fecha timestamp NOT NULL DEFAULT current_timestamp
) ;

--
-- Volcado de datos para la tabla historial_admin
--

INSERT INTO historial_admin (id, usuario_admin, accion, tabla_afectada, id_afectado, detalles, fecha) VALUES
(1, 'root@localhost', 'EDITAR', 'productos', 5, 'Nombre: Juguete Pelota para Perro | Precio: S/6.50 → S/6.50', '2025-07-21 18:55:51'),
(2, 'root@localhost', 'EDITAR', 'productos', 4, 'Stock: 23 → 30 | ', '2025-07-21 19:14:13'),
(3, 'root@localhost', 'EDITAR', 'productos', 6, 'Stock: 17 → 40 | ', '2025-07-21 19:14:45'),
(4, 'root@localhost', 'COMPRA_PROV', 'compras_proveedores', 2, 'Proveedor: dsa | Producto: Limpiador Ayudín Lavanda 900ml | Cant: 20 | Precio: S/60.00', '2025-07-21 21:30:05'),
(5, 'root@localhost', 'EDITAR', 'productos', 122, 'Stock: 60 → 80 | ', '2025-07-21 21:30:05'),
(6, 'root@localhost', 'COMPRA_PROV', 'compras_proveedores', 3, 'Proveedor: dsa | Producto: Limpiador Ayudín Lavanda 900ml | Cant: 20 | Precio: S/60.00', '2025-07-21 21:30:48'),
(7, 'root@localhost', 'EDITAR', 'productos', 122, 'Stock: 80 → 100 | ', '2025-07-21 21:30:48'),
(8, 'root@localhost', 'COMPRA_PROV', 'compras_proveedores', 4, 'Proveedor: SAC | Producto: Collar Antipulgas Bayer | Cant: 50 | Precio: S/50.00', '2025-07-21 21:45:23'),
(9, 'root@localhost', 'EDITAR', 'productos', 6, 'Stock: 40 → 90 | ', '2025-07-21 21:45:23'),
(10, 'root@localhost', 'COMPRA_PROV', 'compras_proveedores', 5, 'Proveedor: SAC | Producto: Collar Antipulgas Bayer | Cant: 50 | Precio: S/50.00', '2025-07-21 21:45:26'),
(11, 'root@localhost', 'EDITAR', 'productos', 6, 'Stock: 90 → 140 | ', '2025-07-21 21:45:26'),
(12, 'root@localhost', 'COMPRA_PROV', 'compras_proveedores', 6, 'Proveedor: SAC2 | Producto: Croquetas para Perro Ricocan 1kg | Cant: 6 | Precio: S/30.00', '2025-07-21 22:04:50'),
(13, 'root@localhost', 'EDITAR', 'productos', 1, 'Stock: 25 → 31 | ', '2025-07-21 22:04:50'),
(14, 'root@localhost', 'COMPRA_PROV', 'compras_proveedores', 7, 'Proveedor: SAC2 | Producto: Detergente Bolívar 1kg | Cant: 30 | Precio: S/13.00', '2025-07-21 22:06:47'),
(15, 'root@localhost', 'EDITAR', 'productos', 19, 'Stock: 98 → 128 | ', '2025-07-21 22:06:47'),
(16, 'root@localhost', 'COMPRA_PROV', 'compras_proveedores', 8, 'Proveedor: MARKET-PROTION-SACCC | Producto: Néctar Gloria Durazno 1L | Cant: 40 | Precio: S/2.00', '2025-07-21 22:27:20'),
(17, 'root@localhost', 'EDITAR', 'productos', 37, 'Stock: 40 → 80 | ', '2025-07-21 22:27:20'),
(18, 'root@localhost', 'EDITAR', 'productos', 21, 'Stock: 88 → 40 | Unidad: 1 Litro → 1 Kilogramos | ', '2025-07-21 22:45:05'),
(19, 'root@localhost', 'EDITAR', 'productos', 180, 'Stock: 50 → 30 | ', '2025-07-21 23:07:22'),
(20, 'root@localhost', 'ELIMINAR', 'productos', 179, 'Producto eliminado: Rexona | Último precio: S/2.30 | Stock final: 50 | Categoría: Cuidado Personal', '2025-07-21 23:07:54'),
(21, 'Admin', 'ELIMINAR', 'productos', 179, 'Se eliminó el producto con ID: 179', '2025-07-21 23:07:54');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla historial_compras
--

CREATE TABLE historial_compras (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  correo_usuario varchar(100) NOT NULL,
  producto varchar(200) NOT NULL,
  precio numeric(10,2) NOT NULL,
  cantidad integer NOT NULL,
  unidad varchar(50) NOT NULL,
  subtotal numeric(10,2) NOT NULL,
  fecha timestamp DEFAULT current_timestamp
) ;

--
-- Volcado de datos para la tabla historial_compras
--

INSERT INTO historial_compras (id, correo_usuario, producto, precio, cantidad, unidad, subtotal, fecha) VALUES
(1, 'juanito@gmail.com', 'Shampoo para Perros PetLife 250ml', 9.50, 1, '250 Mililitros', 9.50, '2025-07-21 02:47:49'),
(2, 'juanito@gmail.com', 'Crema Corporal Nivea Soft 200ml', 12.00, 1, '200 Mililitros', 12.00, '2025-07-21 02:47:49'),
(3, 'juanito@gmail.com', 'Azúcar Rubia Sayón 1kg', 3.50, 1, '1 Kilogramo', 3.50, '2025-07-21 02:47:49'),
(4, 'juanito@gmail.com', 'Arroz Costeño 1kg', 4.80, 1, '1 Kilogramo', 4.80, '2025-07-21 02:47:49'),
(5, 'juanito@gmail.com', 'Alcohol Medicinal 250ml', 2.20, 1, '250 Mililitros', 2.20, '2025-07-21 03:12:24'),
(6, 'juanito@gmail.com', 'Cloro Sapolio 1L', 2.80, 1, '1 Litro', 2.80, '2025-07-21 03:12:24'),
(7, 'juanito@gmail.com', 'Desinfectante Poett Primavera 1L', 6.00, 1, '1 Litro', 6.00, '2025-07-21 03:12:24'),
(8, 'juanito@gmail.com', 'Croquetas para Gato Ricocat 1kg', 13.50, 1, '1 Kilogramos', 13.50, '2025-07-21 03:20:49'),
(9, 'juanito@gmail.com', 'Comedero Doble de Plástico', 7.20, 1, '1 Unidad', 7.20, '2025-07-21 03:25:05'),
(10, 'juanito@gmail.com', 'Arena para Gato CatLitter 4kg', 10.00, 1, '4 Kilogramos', 10.00, '2025-07-21 03:25:05'),
(11, 'juanito@gmail.com', 'Juguete Pelota para Perro', 6.50, 1, '1 Unidad', 6.50, '2025-07-21 03:25:05'),
(12, 'juanito@gmail.com', 'Galletas Dog Chow 500g', 8.00, 1, '500 Gramos', 8.00, '2025-07-21 03:29:57'),
(13, 'juanito@gmail.com', 'Desodorante Axe Dark Temptation 150ml', 13.00, 1, '150 Mililitros', 13.00, '2025-07-21 03:33:33'),
(14, 'juanito@gmail.com', 'Pasta Dental Colgate Triple Acción 90g', 4.20, 1, '90 Gramos', 4.20, '2025-07-21 03:33:33'),
(15, 'juanito@gmail.com', 'Croquetas para Gato Ricocat 1kg', 13.50, 1, '1 Kilogramos', 13.50, '2025-07-21 03:35:00'),
(16, 'juanito@gmail.com', 'Croquetas para Perro Ricocan 1kg', 12.00, 1, '1 Kilogramos', 12.00, '2025-07-21 03:35:00'),
(17, 'juanito@gmail.com', 'Galletas Dog Chow 500g', 8.00, 1, '500 Gramos', 8.00, '2025-07-21 03:44:04'),
(18, 'juanito@gmail.com', 'Croquetas para Gato Ricocat 1kg', 13.50, 1, '1 Kilogramos', 13.50, '2025-07-21 03:44:04'),
(19, 'juanito@gmail.com', 'Croquetas para Gato Ricocat 1kg', 13.50, 1, '1 Kilogramos', 13.50, '2025-07-21 03:47:08'),
(20, 'juanito@gmail.com', 'Jabón Bolívar 3 unidades', 4.20, 1, 'Paquete', 4.20, '2025-07-21 03:50:48'),
(21, 'juanito@gmail.com', 'Jabón Bolívar 3 unidades', 4.20, 1, 'Paquete', 4.20, '2025-07-21 03:50:48'),
(22, 'claudio@gmail.com', 'Juguete Pelota para Perro', 6.50, 1, '1 Unidad', 6.50, '2025-07-21 04:05:37'),
(23, 'claudio@gmail.com', 'Arena para Gato CatLitter 4kg', 10.00, 1, '4 Kilogramos', 10.00, '2025-07-21 04:05:37'),
(24, 'piero@gmail.com', 'Leche Gloria 400g', 4.80, 1, '400 Gramos', 4.80, '2025-07-21 12:59:34'),
(25, 'piero@gmail.com', 'Leche Gloria 400g', 4.80, 1, '400 Gramos', 4.80, '2025-07-21 12:59:34');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla productos
--

CREATE TABLE productos (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre varchar(100) NOT NULL,
  descripcion text DEFAULT NULL,
  precio numeric(10,2) NOT NULL,
  stock integer NOT NULL,
  unidad varchar(50) DEFAULT NULL,
  imagen_url varchar(255) DEFAULT NULL,
  categoria varchar(100) DEFAULT NULL
) ;

--
-- Volcado de datos para la tabla productos
--

INSERT INTO productos (id, nombre, descripcion, precio, stock, unidad, imagen_url, categoria) VALUES
(1, 'Croquetas para Perro Ricocan 1kg', 'Alimento balanceado para perros adultos.', 12.00, 31, '1 Kilogramos', 'mascotas/ricocan-perro.png', 'Mascotas'),
(2, 'Croquetas para Gato Ricocat 1kg', 'Nutrición completa para gatos domésticos.', 13.50, 19, '1 Kilogramos', 'mascotas/ricocat-gato.png', 'Mascotas'),
(3, 'Galletas Dog Chow 500g', 'Snacks para premiar y entrenar perros.', 8.00, 14, '500 Gramos', 'mascotas/dogchow-galletas.png', 'Mascotas'),
(4, 'Arena para Gato CatLitter 4kg', 'Arena absorbente para caja de gato.', 10.00, 30, '4 Kilogramos', 'mascotas/arena-cat.png', 'Mascotas'),
(5, 'Juguete Pelota para Perro', 'Pelota de goma resistente y divertida.', 6.50, 40, '1 Unidad', 'mascotas/pelota-perro.png', 'Mascotas'),
(6, 'Collar Antipulgas Bayer', 'Protección prolongada contra pulgas y garrapatas.', 18.00, 140, '1 Unidad', 'mascotas/collar-bayer.png', 'Mascotas'),
(7, 'Shampoo para Perros PetLife 250ml', 'Limpieza suave con aroma fresco.', 9.50, 26, '250 Mililitros', 'mascotas/shampoo-petlife.png', 'Mascotas'),
(8, 'Comedero Doble de Plástico', 'Tazón doble para comida y agua.', 7.20, 10, '1 Unidad', 'mascotas/comedero-doble.png', 'Mascotas'),
(10, 'Jabón de Tocador Nivea 125g', 'Jabón suave para piel sensible, aroma clásico.', 2.50, 78, '125 Gramos', 'cuidado-personal/jabon-nivea.png', 'Cuidado Personal'),
(11, 'Desodorante Axe Dark Temptation 150ml', 'Aroma duradero para hombres.', 13.00, 57, '150 Mililitros', 'cuidado-personal/desodorante-axe.png', 'Cuidado Personal'),
(12, 'Pasta Dental Colgate Triple Acción 90g', 'Protección anticaries con sabor refrescante.', 4.20, 117, '90 Gramos', 'cuidado-personal/colgate-triple.png', 'Cuidado Personal'),
(13, 'Cepillo de Dientes Oral-B Classic', 'Cepillo de dureza media para uso diario.', 3.80, 99, '1 Unidad', 'cuidado-personal/cepillo-oralb.png', 'Cuidado Personal'),
(14, 'Papel Higiénico Elite x4', 'Rollo doble hoja suave, paquete de 4.', 7.90, 50, '4 Paquete', 'cuidado-personal/papel-elite.png', 'Cuidado Personal'),
(15, 'Crema Corporal Nivea Soft 200ml', 'Hidratación intensa con textura ligera.', 12.00, 29, '200 Mililitros', 'cuidado-personal/crema-nivea.png', 'Cuidado Personal'),
(16, 'Toallas Húmedas Huggies x48', 'Toallitas suaves para bebés y adultos.', 6.50, 40, '1 Paquete', 'cuidado-personal/toallitas-huggies.png', 'Cuidado Personal'),
(17, 'Alcohol Medicinal 250ml', 'Antiséptico desinfectante para heridas.', 2.20, 69, '250 Mililitros', 'cuidado-personal/alcohol-medicinal.png', 'Cuidado Personal'),
(18, 'Hisopos Elite x100', 'Hisopos con algodón puro, envase familiar.', 3.00, 60, 'Paquete', 'cuidado-personal/hisopos-elite.png', 'Cuidado Personal'),
(19, 'Detergente Bolívar 1kg', 'Detergente en polvo para ropa, aroma fresco.', 8.50, 128, '1 Kilogramo', 'limpieza/detergente-bolivar.png', 'Limpieza'),
(20, 'Jabón Bolívar 3 unidades', 'Jabón para lavar ropa a mano, resistente a manchas.', 4.20, 74, 'Paquete', 'limpieza/jabon-bolivar.png', 'Limpieza'),
(21, 'Cloro Sapolio 1L', 'Desinfectante líquido multiuso.', 2.80, 40, '1 Kilogramos', 'limpieza/cloro-sapolio.png', 'Limpieza'),
(22, 'Limpiador Ayudín Lavanda 900ml', 'Limpieza profunda con aroma a lavanda.', 5.50, 57, '900 Mililitros', 'limpieza/limpiador-ayudin.png', 'Limpieza'),
(23, 'Esponja Multiusos Sapolio', 'Esponja duradera para cocina y baño.', 1.80, 98, 'Unidad', 'limpieza/esponja-sapolio.png', 'Limpieza'),
(24, 'Desinfectante Poett Primavera 1L', 'Desinfectante con aroma primaveral.', 6.00, 68, '1 Litro', 'limpieza/poett-primavera.png', 'Limpieza'),
(25, 'Toalla Nova Jumbo', 'Rollo de papel absorbente para cocina.', 5.20, 50, 'Unidad', 'limpieza/toalla-nova.png', 'Limpieza'),
(26, 'Escobilla de baño Sapolio', 'Escobilla plástica con mango resistente.', 4.80, 39, 'Unidad', 'limpieza/escobilla-sapolio.png', 'Limpieza'),
(27, 'Trapeador con palo', 'Trapeador absorbente de uso diario.', 9.00, 30, 'Unidad', 'limpieza/trapeador.png', 'Limpieza'),
(28, 'Bolsas para basura 60L x 10und', 'Bolsas negras resistentes, ideal para hogar.', 4.00, 80, 'Paquete', 'limpieza/bolsas-basura.png', 'Limpieza'),
(29, 'Inka Kola 500ml', 'Gaseosa peruana tradicional, sabor nacional.', 4.50, 98, '500 Mililitros', 'bebidas/inka-kola-500.png', 'Bebidas'),
(30, 'Coca-Cola 1.5L', 'Gaseosa clásica en presentación familiar.', 6.90, 79, '1.5 Litros', 'bebidas/coca-cola-15l.png', 'Bebidas'),
(31, 'Agua Cielo 625ml', 'Agua de mesa purificada, ligera y refrescante.', 2.00, 120, '625 Mililitros', 'bebidas/agua-cielo.png', 'Bebidas'),
(32, 'Gatorade Mandarina 500ml', 'Bebida hidratante sabor mandarina.', 4.20, 49, '500 Mililitros', 'bebidas/gatorade-mandarina.png', 'Bebidas'),
(33, 'Chicha Morada Perú 1L', 'Bebida tradicional hecha con maíz morado.', 5.00, 38, '1 Litro', 'bebidas/chicha-morada.png', 'Bebidas'),
(34, 'Cerveza Cristal 620ml', 'Cerveza peruana lager, ideal para compartir.', 6.00, 69, '620 Mililitros', 'bebidas/cerveza-cristal.png', 'Bebidas'),
(35, 'Cerveza Cusqueña 330ml', 'Cerveza premium originaria de Cusco.', 5.50, 60, '330 Mililitros', 'bebidas/cerveza-cusquena.png', 'Bebidas'),
(36, 'Pilsen Callao 1L', 'Cerveza refrescante con tradición peruana.', 7.00, 50, '1 Litro', 'bebidas/pilsen-callao.png', 'Bebidas'),
(37, 'Néctar Gloria Durazno 1L', 'Néctar de durazno con pulpa de fruta.', 5.50, 80, '1 Litro', 'bebidas/nectar-gloria.png', 'Bebidas'),
(39, 'Frugos Del Valle Mango 500ml', 'Jugo de fruta natural sin gas.', 3.80, 70, '500 Mililitros', 'bebidas/frugos-mango.png', 'Bebidas'),
(40, 'Arroz Costeño 1kg', 'Arroz superior grano largo de la marca Costeño.', 4.80, 98, '1 Kilogramo', 'abarrotes/arroz-costeno.png', 'Abarrotes'),
(41, 'Azúcar Rubia Sayón 1kg', 'Azúcar de caña rubia, ideal para todo uso.', 3.50, 78, '1 Kilogramo', 'abarrotes/azucar-sayon.png', 'Abarrotes'),
(42, 'Fideos Don Vittorio Spaghetti 500g', 'Fideos de trigo fortificados, cocción perfecta.', 3.20, 59, '500 Gramos', 'abarrotes/fideos-donvittorio.png', 'Abarrotes'),
(43, 'Aceite Primor 1L', 'Aceite vegetal refinado ideal para freír y cocinar.', 9.90, 90, '1 Kilogramos', 'abarrotes/aceite-primor.png', 'Abarrotes'),
(44, 'Lentejas Nicolini 500g', 'Lenteja peruana rica en hierro y fibra.', 4.00, 50, '500 Gramos', 'abarrotes/lenteja-nicolini.png', 'Abarrotes'),
(45, 'Harina Blanca Flor 1kg', 'Harina de trigo selecta para repostería.', 4.20, 70, '1 Kilogramo', 'abarrotes/harina-blancaflor.png', 'Abarrotes'),
(46, 'Sal de Mesa Lobos 1kg', 'Sal refinada yodada para uso diario.', 1.20, 120, '1 Kilogramo', 'abarrotes/sal-lobos.png', 'Abarrotes'),
(47, 'Avena 3 Ositos 250g', 'Avena instantánea para desayuno saludable.', 3.80, 45, '250 Gramos', 'abarrotes/avena-3ositos.png', 'Abarrotes'),
(48, 'Leche Gloria 400g', 'Leche evaporada entera ideal para cocina y postres.', 4.80, 84, '400 Gramos', 'abarrotes/leche-gloria.png', 'Abarrotes'),
(49, 'Atún Florida 170g', 'Atún en aceite vegetal marca Florida.', 5.50, 65, '170 Gramos', 'abarrotes/atun-florida.png', 'Abarrotes'),
(50, 'Café Altomayo 170g', 'Café peruano molido de altura, sabor intenso.', 11.00, 40, '170 Gramos', 'abarrotes/cafe-altomayo.png', 'Abarrotes'),
(51, 'Croquetas para Perro Ricocan 1kg', 'Alimento balanceado para perros adultos.', 12.00, 60, '1 Kilogramo', 'mascotas/ricocan-perro.png', 'Mascotas'),
(52, 'Croquetas para Gato Ricocat 1kg', 'Nutrición completa para gatos domésticos.', 13.50, 50, '1 Kilogramo', 'mascotas/ricocat-gato.png', 'Mascotas'),
(53, 'Galletas Dog Chow 500g', 'Snacks para premiar y entrenar perros.', 8.00, 40, '500 Gramos', 'mascotas/dogchow-galletas.png', 'Mascotas'),
(54, 'Arena para Gato CatLitter 4kg', 'Arena absorbente para caja de gato.', 10.00, 30, '4 Kilogramos', 'mascotas/arena-cat.png', 'Mascotas'),
(55, 'Juguete Pelota para Perro', 'Pelota de goma resistente y divertida.', 6.50, 25, 'Unidad', 'mascotas/pelota-perro.png', 'Mascotas'),
(56, 'Collar Antipulgas Bayer', 'Protección prolongada contra pulgas y garrapatas.', 18.00, 20, 'Unidad', 'mascotas/collar-bayer.png', 'Mascotas'),
(57, 'Shampoo para Perros PetLife 250ml', 'Limpieza suave con aroma fresco.', 9.50, 30, '250 Mililitros', 'mascotas/shampoo-petlife.png', 'Mascotas'),
(58, 'Comedero Doble de Plástico', 'Tazón doble para comida y agua.', 7.20, 15, 'Unidad', 'mascotas/comedero-doble.png', 'Mascotas'),
(59, 'Shampoo Sedal 350ml', 'Shampoo para cabello normal, limpieza y brillo.', 10.50, 100, '350 Mililitros', 'cuidado-personal/shampoo-sedal.png', 'Cuidado Personal'),
(60, 'Jabón de Tocador Nivea 125g', 'Jabón suave para piel sensible, aroma clásico.', 2.50, 80, '125 Gramos', 'cuidado-personal/jabon-nivea.png', 'Cuidado Personal'),
(61, 'Desodorante Axe Dark Temptation 150ml', 'Aroma duradero para hombres.', 13.00, 60, '150 Mililitros', 'cuidado-personal/desodorante-axe.png', 'Cuidado Personal'),
(62, 'Pasta Dental Colgate Triple Acción 90g', 'Protección anticaries con sabor refrescante.', 4.20, 120, '90 Gramos', 'cuidado-personal/colgate-triple.png', 'Cuidado Personal'),
(63, 'Cepillo de Dientes Oral-B Classic', 'Cepillo de dureza media para uso diario.', 3.80, 100, 'Unidad', 'cuidado-personal/cepillo-oralb.png', 'Cuidado Personal'),
(64, 'Papel Higiénico Elite x4', 'Rollo doble hoja suave, paquete de 4.', 7.90, 50, 'Paquete', 'cuidado-personal/papel-elite.png', 'Cuidado Personal'),
(65, 'Crema Corporal Nivea Soft 200ml', 'Hidratación intensa con textura ligera.', 12.00, 30, '200 Mililitros', 'cuidado-personal/crema-nivea.png', 'Cuidado Personal'),
(66, 'Toallas Húmedas Huggies x48', 'Toallitas suaves para bebés y adultos.', 6.50, 40, 'Paquete', 'cuidado-personal/toallitas-huggies.png', 'Cuidado Personal'),
(67, 'Alcohol Medicinal 250ml', 'Antiséptico desinfectante para heridas.', 2.20, 70, '250 Mililitros', 'cuidado-personal/alcohol-medicinal.png', 'Cuidado Personal'),
(68, 'Hisopos Elite x100', 'Hisopos con algodón puro, envase familiar.', 3.00, 60, 'Paquete', 'cuidado-personal/hisopos-elite.png', 'Cuidado Personal'),
(69, 'Detergente Bolívar 1kg', 'Detergente en polvo para ropa, aroma fresco.', 8.50, 100, '1 Kilogramo', 'limpieza/detergente-bolivar.png', 'Limpieza'),
(70, 'Jabón Bolívar 3 unidades', 'Jabón para lavar ropa a mano, resistente a manchas.', 4.20, 79, 'Paquete', 'limpieza/jabon-bolivar.png', 'Limpieza'),
(71, 'Cloro Sapolio 1L', 'Desinfectante líquido multiuso.', 2.80, 90, '1 Litro', 'limpieza/cloro-sapolio.png', 'Limpieza'),
(72, 'Limpiador Ayudín Lavanda 900ml', 'Limpieza profunda con aroma a lavanda.', 5.50, 60, '900 Mililitros', 'limpieza/limpiador-ayudin.png', 'Limpieza'),
(73, 'Esponja Multiusos Sapolio', 'Esponja duradera para cocina y baño.', 1.80, 100, 'Unidad', 'limpieza/esponja-sapolio.png', 'Limpieza'),
(74, 'Desinfectante Poett Primavera 1L', 'Desinfectante con aroma primaveral.', 6.00, 70, '1 Litro', 'limpieza/poett-primavera.png', 'Limpieza'),
(75, 'Toalla Nova Jumbo', 'Rollo de papel absorbente para cocina.', 5.20, 50, 'Unidad', 'limpieza/toalla-nova.png', 'Limpieza'),
(76, 'Escobilla de baño Sapolio', 'Escobilla plástica con mango resistente.', 4.80, 40, 'Unidad', 'limpieza/escobilla-sapolio.png', 'Limpieza'),
(77, 'Trapeador con palo', 'Trapeador absorbente de uso diario.', 9.00, 30, 'Unidad', 'limpieza/trapeador.png', 'Limpieza'),
(78, 'Bolsas para basura 60L x 10und', 'Bolsas negras resistentes, ideal para hogar.', 4.00, 80, 'Paquete', 'limpieza/bolsas-basura.png', 'Limpieza'),
(79, 'Inka Kola 500ml', 'Gaseosa peruana tradicional, sabor nacional.', 4.50, 100, '500 Mililitros', 'bebidas/inka-kola-500.png', 'Bebidas'),
(80, 'Coca-Cola 1.5L', 'Gaseosa clásica en presentación familiar.', 6.90, 80, '1.5 Litros', 'bebidas/coca-cola-15l.png', 'Bebidas'),
(81, 'Agua Cielo 625ml', 'Agua de mesa purificada, ligera y refrescante.', 2.00, 120, '625 Mililitros', 'bebidas/agua-cielo.png', 'Bebidas'),
(82, 'Gatorade Mandarina 500ml', 'Bebida hidratante sabor mandarina.', 4.20, 50, '500 Mililitros', 'bebidas/gatorade-mandarina.png', 'Bebidas'),
(83, 'Chicha Morada Perú 1L', 'Bebida tradicional hecha con maíz morado.', 5.00, 40, '1 Litro', 'bebidas/chicha-morada.png', 'Bebidas'),
(84, 'Cerveza Cristal 620ml', 'Cerveza peruana lager, ideal para compartir.', 6.00, 70, '620 Mililitros', 'bebidas/cerveza-cristal.png', 'Bebidas'),
(85, 'Cerveza Cusqueña 330ml', 'Cerveza premium originaria de Cusco.', 5.50, 60, '330 Mililitros', 'bebidas/cerveza-cusquena.png', 'Bebidas'),
(86, 'Pilsen Callao 1L', 'Cerveza refrescante con tradición peruana.', 7.00, 50, '1 Litro', 'bebidas/pilsen-callao.png', 'Bebidas'),
(87, 'Néctar Gloria Durazno 1L', 'Néctar de durazno con pulpa de fruta.', 5.50, 40, '1 Litro', 'bebidas/nectar-gloria.png', 'Bebidas'),
(89, 'Frugos Del Valle Mango 500ml', 'Jugo de fruta natural sin gas.', 3.80, 70, '500 Mililitros', 'bebidas/frugos-mango.png', 'Bebidas'),
(90, 'Arroz Costeño 1kg', 'Arroz superior grano largo de la marca Costeño.', 4.80, 100, '1 Kilogramo', 'abarrotes/arroz-costeno.png', 'Abarrotes'),
(91, 'Azúcar Rubia Sayón 1kg', 'Azúcar de caña rubia, ideal para todo uso.', 3.50, 80, '1 Kilogramo', 'abarrotes/azucar-sayon.png', 'Abarrotes'),
(92, 'Fideos Don Vittorio Spaghetti 500g', 'Fideos de trigo fortificados, cocción perfecta.', 3.20, 60, '500 Gramos', 'abarrotes/fideos-donvittorio.png', 'Abarrotes'),
(93, 'Aceite Primor 1L', 'Aceite vegetal refinado ideal para freír y cocinar.', 9.90, 90, '1 Litro', 'abarrotes/aceite-primor.png', 'Abarrotes'),
(94, 'Lentejas Nicolini 500g', 'Lenteja peruana rica en hierro y fibra.', 4.00, 50, '500 Gramos', 'abarrotes/lenteja-nicolini.png', 'Abarrotes'),
(95, 'Harina Blanca Flor 1kg', 'Harina de trigo selecta para repostería.', 4.20, 70, '1 Kilogramo', 'abarrotes/harina-blancaflor.png', 'Abarrotes'),
(96, 'Sal de Mesa Lobos 1kg', 'Sal refinada yodada para uso diario.', 1.20, 120, '1 Kilogramo', 'abarrotes/sal-lobos.png', 'Abarrotes'),
(97, 'Avena 3 Ositos 250g', 'Avena instantánea para desayuno saludable.', 3.80, 45, '250 Gramos', 'abarrotes/avena-3ositos.png', 'Abarrotes'),
(98, 'Leche Gloria 400g', 'Leche evaporada entera ideal para cocina y postres.', 4.80, 84, '400 Gramos', 'abarrotes/leche-gloria.png', 'Abarrotes'),
(99, 'Atún Florida 170g', 'Atún en aceite vegetal marca Florida.', 5.50, 65, '170 Gramos', 'abarrotes/atun-florida.png', 'Abarrotes'),
(100, 'Café Altomayo 170g', 'Café peruano molido de altura, sabor intenso.', 11.00, 40, '170 Gramos', 'abarrotes/cafe-altomayo.png', 'Abarrotes'),
(101, 'Croquetas para Perro Ricocan 1kg', 'Alimento balanceado para perros adultos.', 12.00, 60, '1 Kilogramo', 'mascotas/ricocan-perro.png', 'Mascotas'),
(102, 'Croquetas para Gato Ricocat 1kg', 'Nutrición completa para gatos domésticos.', 13.50, 50, '1 Kilogramo', 'mascotas/ricocat-gato.png', 'Mascotas'),
(103, 'Galletas Dog Chow 500g', 'Snacks para premiar y entrenar perros.', 8.00, 40, '500 Gramos', 'mascotas/dogchow-galletas.png', 'Mascotas'),
(104, 'Arena para Gato CatLitter 4kg', 'Arena absorbente para caja de gato.', 10.00, 30, '4 Kilogramos', 'mascotas/arena-cat.png', 'Mascotas'),
(105, 'Juguete Pelota para Perro', 'Pelota de goma resistente y divertida.', 6.50, 25, 'Unidad', 'mascotas/pelota-perro.png', 'Mascotas'),
(106, 'Collar Antipulgas Bayer', 'Protección prolongada contra pulgas y garrapatas.', 18.00, 20, 'Unidad', 'mascotas/collar-bayer.png', 'Mascotas'),
(107, 'Shampoo para Perros PetLife 250ml', 'Limpieza suave con aroma fresco.', 9.50, 30, '250 Mililitros', 'mascotas/shampoo-petlife.png', 'Mascotas'),
(108, 'Comedero Doble de Plástico', 'Tazón doble para comida y agua.', 7.20, 15, 'Unidad', 'mascotas/comedero-doble.png', 'Mascotas'),
(109, 'Shampoo Sedal 350ml', 'Shampoo para cabello normal, limpieza y brillo.', 10.50, 100, '350 Mililitros', 'cuidado-personal/shampoo-sedal.png', 'Cuidado Personal'),
(110, 'Jabón de Tocador Nivea 125g', 'Jabón suave para piel sensible, aroma clásico.', 2.50, 80, '125 Gramos', 'cuidado-personal/jabon-nivea.png', 'Cuidado Personal'),
(111, 'Desodorante Axe Dark Temptation 150ml', 'Aroma duradero para hombres.', 13.00, 60, '150 Mililitros', 'cuidado-personal/desodorante-axe.png', 'Cuidado Personal'),
(112, 'Pasta Dental Colgate Triple Acción 90g', 'Protección anticaries con sabor refrescante.', 4.20, 120, '90 Gramos', 'cuidado-personal/colgate-triple.png', 'Cuidado Personal'),
(113, 'Cepillo de Dientes Oral-B Classic', 'Cepillo de dureza media para uso diario.', 3.80, 100, 'Unidad', 'cuidado-personal/cepillo-oralb.png', 'Cuidado Personal'),
(114, 'Papel Higiénico Elite x4', 'Rollo doble hoja suave, paquete de 4.', 7.90, 50, 'Paquete', 'cuidado-personal/papel-elite.png', 'Cuidado Personal'),
(115, 'Crema Corporal Nivea Soft 200ml', 'Hidratación intensa con textura ligera.', 12.00, 30, '200 Mililitros', 'cuidado-personal/crema-nivea.png', 'Cuidado Personal'),
(116, 'Toallas Húmedas Huggies x48', 'Toallitas suaves para bebés y adultos.', 6.50, 40, 'Paquete', 'cuidado-personal/toallitas-huggies.png', 'Cuidado Personal'),
(117, 'Alcohol Medicinal 250ml', 'Antiséptico desinfectante para heridas.', 2.20, 70, '250 Mililitros', 'cuidado-personal/alcohol-medicinal.png', 'Cuidado Personal'),
(118, 'Hisopos Elite x100', 'Hisopos con algodón puro, envase familiar.', 3.00, 60, 'Paquete', 'cuidado-personal/hisopos-elite.png', 'Cuidado Personal'),
(119, 'Detergente Bolívar 1kg', 'Detergente en polvo para ropa, aroma fresco.', 8.50, 100, '1 Kilogramo', 'limpieza/detergente-bolivar.png', 'Limpieza'),
(120, 'Jabón Bolívar 3 unidades', 'Jabón para lavar ropa a mano, resistente a manchas.', 4.20, 80, 'Paquete', 'limpieza/jabon-bolivar.png', 'Limpieza'),
(121, 'Cloro Sapolio 1L', 'Desinfectante líquido multiuso.', 2.80, 90, '1 Litro', 'limpieza/cloro-sapolio.png', 'Limpieza'),
(122, 'Limpiador Ayudín Lavanda 900ml', 'Limpieza profunda con aroma a lavanda.', 5.50, 100, '900 Mililitros', 'limpieza/limpiador-ayudin.png', 'Limpieza'),
(123, 'Esponja Multiusos Sapolio', 'Esponja duradera para cocina y baño.', 1.80, 100, 'Unidad', 'limpieza/esponja-sapolio.png', 'Limpieza'),
(124, 'Desinfectante Poett Primavera 1L', 'Desinfectante con aroma primaveral.', 6.00, 70, '1 Litro', 'limpieza/poett-primavera.png', 'Limpieza'),
(125, 'Toalla Nova Jumbo', 'Rollo de papel absorbente para cocina.', 5.20, 50, 'Unidad', 'limpieza/toalla-nova.png', 'Limpieza'),
(126, 'Escobilla de baño Sapolio', 'Escobilla plástica con mango resistente.', 4.80, 40, 'Unidad', 'limpieza/escobilla-sapolio.png', 'Limpieza'),
(127, 'Trapeador con palo', 'Trapeador absorbente de uso diario.', 9.00, 30, 'Unidad', 'limpieza/trapeador.png', 'Limpieza'),
(128, 'Bolsas para basura 60L x 10und', 'Bolsas negras resistentes, ideal para hogar.', 4.00, 80, 'Paquete', 'limpieza/bolsas-basura.png', 'Limpieza'),
(129, 'Inka Kola 500ml', 'Gaseosa peruana tradicional, sabor nacional.', 4.50, 100, '500 Mililitros', 'bebidas/inka-kola-500.png', 'Bebidas'),
(130, 'Coca-Cola 1.5L', 'Gaseosa clásica en presentación familiar.', 6.90, 80, '1.5 Litros', 'bebidas/coca-cola-15l.png', 'Bebidas'),
(131, 'Agua Cielo 625ml', 'Agua de mesa purificada, ligera y refrescante.', 2.00, 120, '625 Mililitros', 'bebidas/agua-cielo.png', 'Bebidas'),
(132, 'Gatorade Mandarina 500ml', 'Bebida hidratante sabor mandarina.', 4.20, 50, '500 Mililitros', 'bebidas/gatorade-mandarina.png', 'Bebidas'),
(133, 'Chicha Morada Perú 1L', 'Bebida tradicional hecha con maíz morado.', 5.00, 40, '1 Litro', 'bebidas/chicha-morada.png', 'Bebidas'),
(134, 'Cerveza Cristal 620ml', 'Cerveza peruana lager, ideal para compartir.', 6.00, 69, '620 Mililitros', 'bebidas/cerveza-cristal.png', 'Bebidas'),
(135, 'Cerveza Cusqueña 330ml', 'Cerveza premium originaria de Cusco.', 5.50, 60, '330 Mililitros', 'bebidas/cerveza-cusquena.png', 'Bebidas'),
(136, 'Pilsen Callao 1L', 'Cerveza refrescante con tradición peruana.', 7.00, 50, '1 Litro', 'bebidas/pilsen-callao.png', 'Bebidas'),
(137, 'Néctar Gloria Durazno 1L', 'Néctar de durazno con pulpa de fruta.', 5.50, 40, '1 Litro', 'bebidas/nectar-gloria.png', 'Bebidas'),
(138, 'Emoliente Natural 500ml', 'Bebida tradicional con hierbas digestivas.', 3.00, 30, '500 Mililitros', 'bebidas/emoliente.png', 'Bebidas'),
(139, 'Frugos Del Valle Mango 500ml', 'Jugo de fruta natural sin gas.', 3.80, 70, '500 Mililitros', 'bebidas/frugos-mango.png', 'Bebidas'),
(140, 'Arroz Costeño 1kg', 'Arroz superior grano largo de la marca Costeño.', 4.80, 100, '1 Kilogramo', 'abarrotes/arroz-costeno.png', 'Abarrotes'),
(141, 'Azúcar Rubia Sayón 1kg', 'Azúcar de caña rubia, ideal para todo uso.', 3.50, 80, '1 Kilogramo', 'abarrotes/azucar-sayon.png', 'Abarrotes'),
(142, 'Fideos Don Vittorio Spaghetti 500g', 'Fideos de trigo fortificados, cocción perfecta.', 3.20, 60, '500 Gramos', 'abarrotes/fideos-donvittorio.png', 'Abarrotes'),
(143, 'Aceite Primor 1L', 'Aceite vegetal refinado ideal para freír y cocinar.', 9.90, 90, '1 Litro', 'abarrotes/aceite-primor.png', 'Abarrotes'),
(144, 'Lentejas Nicolini 500g', 'Lenteja peruana rica en hierro y fibra.', 4.00, 50, '500 Gramos', 'abarrotes/lenteja-nicolini.png', 'Abarrotes'),
(145, 'Harina Blanca Flor 1kg', 'Harina de trigo selecta para repostería.', 4.20, 70, '1 Kilogramo', 'abarrotes/harina-blancaflor.png', 'Abarrotes'),
(146, 'Sal de Mesa Lobos 1kg', 'Sal refinada yodada para uso diario.', 1.20, 120, '1 Kilogramo', 'abarrotes/sal-lobos.png', 'Abarrotes'),
(147, 'Avena 3 Ositos 250g', 'Avena instantánea para desayuno saludable.', 3.80, 45, '250 Gramos', 'abarrotes/avena-3ositos.png', 'Abarrotes'),
(148, 'Leche Gloria 400g', 'Leche evaporada entera ideal para cocina y postres.', 4.80, 85, '400 Gramos', 'abarrotes/leche-gloria.png', 'Abarrotes'),
(149, 'Atún Florida 170g', 'Atún en aceite vegetal marca Florida.', 5.50, 65, '170 Gramos', 'abarrotes/atun-florida.png', 'Abarrotes'),
(150, 'Café Altomayo 170g', 'Café peruano molido de altura, sabor intenso.', 11.00, 40, '170 Gramos', 'abarrotes/cafe-altomayo.png', 'Abarrotes'),
(151, 'Fresas 250g', 'Fresas frescas y jugosas, cultivadas localmente.', 5.00, 30, '250 Gramos', 'frutas/fresa.png', 'Frutas'),
(152, 'Mandarina 1kg', 'Mandarina dulce y fácil de pelar.', 4.50, 40, '1 Kilogramo', 'frutas/mandarina.png', 'Frutas'),
(153, 'Mango 1 unidad', 'Mango maduro y dulce, ideal para jugos o postres.', 3.00, 25, 'Unidad', 'frutas/mango.png', 'Frutas'),
(154, 'Manzana Roja 1kg', 'Manzana crujiente y refrescante.', 6.00, 35, '1 Kilogramo', 'frutas/manzana.png', 'Frutas'),
(155, 'Naranja 1kg', 'Naranjas jugosas ricas en vitamina C.', 3.80, 50, '1 Kilogramo', 'frutas/naranja.png', 'Frutas'),
(156, 'Papaya 1 unidad', 'Papaya madura y dulce, perfecta para desayunos.', 7.00, 20, 'Unidad', 'frutas/papaya.png', 'Frutas'),
(157, 'Piña 1 unidad', 'Piña fresca y aromática.', 8.50, 15, 'Unidad', 'frutas/pina.png', 'Frutas'),
(158, 'Plátano Isla 1kg', 'Plátano de seda, ideal para hervir o freír.', 2.10, 30, '1 Kilogramos', 'frutas/platano-isla.png', 'Frutas'),
(159, 'Plátano 1kg', 'Plátano común, versátil en cocina.', 2.30, 40, '1 Kilogramos', 'frutas/platano.png', 'Frutas'),
(160, 'Sandía 1 unidad', 'Sandía fresca y refrescante.', 12.00, 10, 'Unidad', 'frutas/sandia.png', 'Frutas'),
(161, 'Ají Amarillo 100g', 'Ají peruano picante, esencial para salsas.', 2.50, 60, '100 Gramos', 'verduras/aji-amarillo.png', 'Verduras'),
(162, 'Arveja 200g', 'Arvejas frescas, ricas en proteínas.', 2.50, 20, '200 Gramos', 'verduras/arveja.png', 'Verduras'),
(163, 'Apio 1 unidad', 'Apio fresco para sopas y ensaladas.', 2.00, 27, 'Unidad', 'verduras/apio.png', 'Verduras'),
(164, 'Betarraga 1kg', 'Betarraga dulce y nutritiva.', 4.00, 25, '1 Kilogramo', 'verduras/betarraga.png', 'Verduras'),
(165, 'Camote Morado 1kg', 'Camote morado rico en antioxidantes.', 5.50, 20, '1 Kilogramo', 'verduras/camote-morado.png', 'Verduras'),
(166, 'Cebolla Roja 1kg', 'Cebolla roja ideal para ensaladas.', 3.50, 40, '1 Kilogramo', 'verduras/cebolla-roja.png', 'Verduras'),
(167, 'Culantro 1 atado', 'Culantro fresco para aderezar comidas.', 1.50, 50, 'Atado', 'verduras/culantro.png', 'Verduras'),
(168, 'Espinaca 1 atado', 'Espinaca fresca, rica en hierro.', 2.80, 35, 'Atado', 'verduras/espinaca.png', 'Verduras'),
(169, 'Lechuga Americana 1 unidad', 'Lechuga crujiente para ensaladas.', 3.00, 30, 'Unidad', 'verduras/lechuga-americana.png', 'Verduras'),
(170, 'Papa Amarilla 1kg', 'Papa amarilla peruana, ideal para puré.', 4.00, 60, '1 Kilogramo', 'verduras/papa-amarilla.png', 'Verduras'),
(171, 'Tomate 1kg', 'Tomate fresco para salsas y ensaladas.', 5.00, 40, '1 Kilogramo', 'verduras/tomate.png', 'Verduras'),
(172, 'Yuca 1kg', 'Yuca fresca, perfecta para freír o sancochar.', 4.50, 25, '1 Kilogramo', 'verduras/yuca.png', 'Verduras'),
(173, 'Zapallo Macre 1kg', 'Zapallo macre, dulce y versátil.', 6.00, 15, '1 Kilogramo', 'verduras/zapallo-macre.png', 'Verduras'),
(174, 'Gelatina', 'Para refrescarse', 1.20, 20, '1 Unidad', 'images/abarrotes/gelatia.png', 'Abarrotes'),
(175, 'Vino Rosé Semiseco Santiago Queirolo 750 ml', 'Vino', 15.00, 33, '750 Mililitros', 'bebidas/rous.png', 'Bebidas'),
(176, 'Vino Borgoña Santiago Queirolo 750 ml', 'Vino', 16.00, 24, '750 Mililitros', 'bebidas/borgona.png', 'Bebidas'),
(177, 'Vino Magdalena Santiago Queirolo 750 ml', 'Vino', 18.00, 29, '750 Mililitros', 'bebidas/magdalena.png', 'Bebidas'),
(178, 'Plátano Bellaco', 'Para freir', 3.00, 29, '1 Kilogramos', 'frutas/bellaco.jpg', 'Frutas'),
(180, 'Rexona', 'Rexona men V8 ', 2.30, 30, '10 Gramos', 'cuidado-personal/AXEsh.jpg', 'Limpieza');

--
-- Disparadores productos
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla proveedores
--

CREATE TABLE proveedores (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre varchar(100) NOT NULL,
  ruc varchar(11) NOT NULL,
  contacto varchar(100) DEFAULT NULL,
  telefono varchar(20) DEFAULT NULL,
  direccion text DEFAULT NULL,
  tipo varchar(50) NOT NULL,
  evaluacion smallint DEFAULT 5 ,
  fecha_registro timestamp NOT NULL DEFAULT current_timestamp,
  activo smallint DEFAULT 1
) ;

--
-- Volcado de datos para la tabla proveedores
--

INSERT INTO proveedores (id, nombre, ruc, contacto, telefono, direccion, tipo, evaluacion, fecha_registro, activo) VALUES
(1, 'dsa', '22222222222', 'dsada', 'das', NULL, 'Abarrotes', 5, '2025-07-21 21:21:12', 0),
(6, 'SAC', '12354568741', '1425456', '', NULL, 'Licores', 5, '2025-07-21 21:40:45', 1),
(7, 'SAC2', '12345678914', '14564', '13513', NULL, 'Limpieza', 5, '2025-07-21 22:04:24', 1),
(8, 'MARKET-PROTION-SACCC', '12345612378', '123456789', '123456', NULL, 'Frutas/Verduras', 5, '2025-07-21 22:26:42', 1);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla usuarios
--

CREATE TABLE usuarios (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nombre varchar(100) NOT NULL,
  apellidos varchar(100) NOT NULL,
  correo varchar(100) NOT NULL,
  contrasena varchar(255) NOT NULL
) ;

--
-- Volcado de datos para la tabla usuarios
--

INSERT INTO usuarios (id, nombre, apellidos, correo, contrasena) VALUES
(1, 'JUANES1', 'JUANES1', 'JUANES1@gmail.com', '123'),
(2, 'SANTOS', 'SANTOS', 'SANTOS@gmail.com', 'SANTOS'),
(3, 'RENZO', 'RENZO', 'RENZO@gmail.com', 'RENZO'),
(4, 'SANCHES', 'Sanches Otomano', 'SANCHES@gmail.com', '123456'),
(5, 'CLAU', 'CLAU', 'clau@gmail.com', ''),
(6, 'Juanito', 'Juanito', 'juanito@gmail.com', '123456'),
(7, 'Sandro', 'Sandro', 'sandro@gmail.com', '123456'),
(8, 'Piero', 'Pierio', 'piero@gmail.com', '123456');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla admin
--
ALTER TABLE admin
  ADD PRIMARY KEY (id);

--
-- Indices de la tabla comentarios
--
ALTER TABLE comentarios
  ADD PRIMARY KEY (id);

--
-- Indices de la tabla compras_proveedores
--
ALTER TABLE compras_proveedores
  ADD PRIMARY KEY (id);

--
-- Indices de la tabla historial_admin
--
ALTER TABLE historial_admin
  ADD PRIMARY KEY (id);

--
-- Indices de la tabla historial_compras
--
ALTER TABLE historial_compras
  ADD PRIMARY KEY (id);

--
-- Indices de la tabla productos
--
ALTER TABLE productos
  ADD PRIMARY KEY (id);

--
-- Indices de la tabla proveedores
--
ALTER TABLE proveedores
  ADD PRIMARY KEY (id),
  ADD CONSTRAINT ruc UNIQUE (ruc);

--
-- Indices de la tabla usuarios
--
ALTER TABLE usuarios
  ADD PRIMARY KEY (id),
  ADD CONSTRAINT correo UNIQUE (correo);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla admin
--

--
-- AUTO_INCREMENT de la tabla comentarios
--

--
-- AUTO_INCREMENT de la tabla compras_proveedores
--

--
-- AUTO_INCREMENT de la tabla historial_admin
--

--
-- AUTO_INCREMENT de la tabla historial_compras
--

--
-- AUTO_INCREMENT de la tabla productos
--

--
-- AUTO_INCREMENT de la tabla proveedores
--

--
-- AUTO_INCREMENT de la tabla usuarios
--

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla compras_proveedores
--
ALTER TABLE compras_proveedores
  ADD CONSTRAINT compras_proveedores_ibfk_1 FOREIGN KEY (proveedor_id) REFERENCES proveedores (id),
  ADD CONSTRAINT compras_proveedores_ibfk_2 FOREIGN KEY (producto_id) REFERENCES productos (id);


-- ============================================================
-- Triggers migrados de MariaDB a PostgreSQL
-- ============================================================

CREATE OR REPLACE FUNCTION trg_after_compra_proveedor() RETURNS TRIGGER AS $$
DECLARE
  nombre_prov varchar(100);
  nombre_prod varchar(100);
BEGIN
  SELECT nombre INTO nombre_prov FROM proveedores WHERE id = NEW.proveedor_id;
  SELECT nombre INTO nombre_prod FROM productos WHERE id = NEW.producto_id;
  INSERT INTO historial_admin (usuario_admin, accion, tabla_afectada, id_afectado, detalles)
  VALUES (CURRENT_USER, 'COMPRA_PROV', 'compras_proveedores', NEW.id,
    'Proveedor: ' || nombre_prov || ' | Producto: ' || nombre_prod || ' | Cant: ' || NEW.cantidad || ' | Precio: S/' || NEW.precio_unitario);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_compra_proveedor AFTER INSERT ON compras_proveedores
FOR EACH ROW EXECUTE FUNCTION trg_after_compra_proveedor();

CREATE OR REPLACE FUNCTION trg_after_producto_delete() RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO historial_admin (usuario_admin, accion, tabla_afectada, id_afectado, detalles)
  VALUES (CURRENT_USER, 'ELIMINAR', 'productos', OLD.id,
    'Producto eliminado: ' || OLD.nombre || ' | Ultimo precio: S/' || OLD.precio || ' | Stock final: ' || OLD.stock || ' | Categoria: ' || OLD.categoria);
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_producto_delete AFTER DELETE ON productos
FOR EACH ROW EXECUTE FUNCTION trg_after_producto_delete();

CREATE OR REPLACE FUNCTION trg_after_producto_update() RETURNS TRIGGER AS $$
DECLARE
  cambios text;
BEGIN
  cambios :=
    CASE WHEN NEW.nombre IS DISTINCT FROM OLD.nombre THEN 'Nombre: ' || OLD.nombre || ' -> ' || NEW.nombre || ' | ' ELSE '' END ||
    CASE WHEN NEW.descripcion IS DISTINCT FROM OLD.descripcion THEN 'Descripcion: ' || LEFT(OLD.descripcion, 20) || '... -> ' || LEFT(NEW.descripcion, 20) || '... | ' ELSE '' END ||
    CASE WHEN NEW.precio IS DISTINCT FROM OLD.precio THEN 'Precio: S/' || OLD.precio || ' -> S/' || NEW.precio || ' | ' ELSE '' END ||
    CASE WHEN NEW.stock IS DISTINCT FROM OLD.stock THEN 'Stock: ' || OLD.stock || ' -> ' || NEW.stock || ' | ' ELSE '' END ||
    CASE WHEN NEW.unidad IS DISTINCT FROM OLD.unidad THEN 'Unidad: ' || OLD.unidad || ' -> ' || NEW.unidad || ' | ' ELSE '' END ||
    CASE WHEN NEW.imagen_url IS DISTINCT FROM OLD.imagen_url THEN 'Imagen: Cambiada | ' ELSE '' END ||
    CASE WHEN NEW.categoria IS DISTINCT FROM OLD.categoria THEN 'Categoria: ' || OLD.categoria || ' -> ' || NEW.categoria || ' | ' ELSE '' END;
  IF cambios <> '' THEN
    INSERT INTO historial_admin (usuario_admin, accion, tabla_afectada, id_afectado, detalles)
    VALUES (CURRENT_USER, 'EDITAR', 'productos', OLD.id, cambios);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_producto_update AFTER UPDATE ON productos
FOR EACH ROW EXECUTE FUNCTION trg_after_producto_update();

-- Reinicio de secuencias IDENTITY al valor AUTO_INCREMENT original
SELECT setval(pg_get_serial_sequence('admin', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM admin), 0), 2 - 1));
SELECT setval(pg_get_serial_sequence('compras_proveedores', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM compras_proveedores), 0), 9 - 1));
SELECT setval(pg_get_serial_sequence('historial_admin', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM historial_admin), 0), 22 - 1));
SELECT setval(pg_get_serial_sequence('historial_compras', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM historial_compras), 0), 26 - 1));
SELECT setval(pg_get_serial_sequence('productos', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM productos), 0), 181 - 1));
SELECT setval(pg_get_serial_sequence('proveedores', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM proveedores), 0), 9 - 1));
SELECT setval(pg_get_serial_sequence('usuarios', 'id'), GREATEST(COALESCE((SELECT MAX(id) FROM usuarios), 0), 9 - 1));
